name: Build and release
on:
  push:
    branches:
      - publish
    tags:
      - 'v1.0.1'
  pull_request:
    branches:
      - publish
jobs:
  build:
    name: sbt assembly
    runs-on: ubuntu-latest
    container:
      image: eed3si9n/sbt:jdk11-alpine
    steps:
      - uses: actions/checkout@v2
      - name: sbt assembly
        run: sbt 'set assemblyOutputPath in assembly := new File("./target/alist.jar")' assembly
      - uses: actions/upload-artifact@v2
        with:
          path: target/alist.jar

  release_jar:
    name: jar-image
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          path: ./
      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: 'artifact/alist.jar'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}